### ISSUE TITLE
issue with 5.6 laravel : Undefined method share()

### ISSUE THREAD

**Issue by drashtiSeo** [padosoft/laravel-google-structured-data-testing-tool#4]
[QUESTION]

I have install this package using 
composer require padosoft/laravel-google-structured-data-testing-tool

also declare class in provider but when I am going to use
php artisan vendor:publish --provider="Padosoft\Laravel\Google\StructuredDataTestingTool\GoogleStructuredDataTestToolServiceProvider"
command It will gives me error as below : 

Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Illuminate\Foundation\Application::share()

at D:\xampp\htdocs\seoMgt\vendor\padosoft\laravel-google-structured-data-testing-tool\src\GoogleStructuredDataTestToolServiceProvider.php:40

**Comment by lopadova** [comment]
Hi @drashtiSeo 
I Fix the package for Laravel 5.4+.
The problem was: app->share is deprecated in laravel 5.4.
I use app->singleton instead.
Thanks.

**Comment by drashtiSeo** [comment]
Oh thanks for the solution.
I already do that and its working.

Thanks @lopadova
